name: Docker build and push

on:
  workflow_dispatch:
    inputs:
      version: 'v1.0'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:${{ github.event.release.release.name }}
      - run: echo ${{ github.ref }}
