name: Docker Image CI

on:
  release:
    types: [published]
  repository_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:${{ github.event.release.release.name }}
      - run: echo "debug::${{ github.event.release }}"
