name: Docker publish

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1.8.0
      name: Login to docker
      with:
        username: 'richardhofmaenner'
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: |
          richardhofmaenner/onlydevs-frontend:latest
          richardhofmaenner/onlydevs-frontend:${{ github.event.release.tag_name }}
